version: "3.9"

services:
  app:
    container_name: hit-the-phrase-ts
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=username
      - DB_PASS=password
      - DB_NAME=dbname
  # db:
  #   container_name: hit-the-phrase-ts-db
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_USER=username
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=dbname
  #   ports:
  #     - "5432:5432"
